export const projects = [
  {
    title: "Modern Villa Projesi",
    slug: "modern-villa",
    category: "Konut",
    location: "İstanbul, Türkiye",
    year: 2024,
    description: "Minimalist çizgilerle tasarlanmış lüks villa projesi.",
  },
  {
    title: "Ofis Kompleksi",
    slug: "ofis-kompleksi",
    category: "Ticari",
    location: "Ankara, Türkiye",
    year: 2023,
    description: "Sürdürülebilir tasarım ilkeleriyle inşa edilen ofis kompleksi.",
  },
  {
    title: "Butik Otel Tasarımı",
    slug: "butik-otel",
    category: "Konaklama",
    location: "Bodrum, Türkiye",
    year: 2023,
    description: "Doğayla iç içe, modern bir butik otel projesi.",
  },
  {
    title: "Kültür Merkezi",
    slug: "kultur-merkezi",
    category: "Kamusal",
    location: "İzmir, Türkiye",
    year: 2022,
    description: "Şehrin kültürel yaşamına katkı sunan çok amaçlı kültür merkezi.",
  },
  {
    title: "Loft Daire Renovasyon",
    slug: "loft-renovasyon",
    category: "Renovasyon",
    location: "İstanbul, Türkiye",
    year: 2024,
    description: "Endüstriyel dokunuşlarla yenilenen loft daire projesi.",
  },
  {
    title: "Peyzaj Parkı",
    slug: "peyzaj-parki",
    category: "Peyzaj",
    location: "Bursa, Türkiye",
    year: 2023,
    description: "Şehir merkezinde doğayla buluşturan yeşil alan projesi.",
  },
];
