export const projects = [
  {
    title: "Modern Ahşap Kış Bahçesi PRO-MAX",
    slug: "modern-ahsap-kis-bahcesi-pro-max",
    category: "Kış Bahçesi",
    location: "Kayseri, Türkiye",
    year: 2026,
    description: "Modern hatlara sahip, her mevsime uygun dayanıklı kış bahçesi projesi.",
    image: "/images/projects/modern-ahsap-kis-bahcesi.jpg",
    longDescription:
      "PRO-MAX serisi kış bahçelerimiz; yüksek ısı yalıtımı, anti-UV cam sistemleri ve premium Sibirya çamı konstrüksiyonu ile tüm iklim koşullarına meydan okur. Her modül, fabrikamızda CNC işleme tezgâhlarında hassasiyetle üretilerek sahaya taşınmaktadır.",
    features: [
      { label: "Malzeme", value: "Sibirya Çamı (1. Sınıf)" },
      { label: "Cam Sistemi", value: "Çift Isıcam, Anti-UV Kaplama" },
      { label: "Alan", value: "24 m²" },
      { label: "Isı Yalıtımı", value: "Rockwool + Alüminyum Folyo" },
      { label: "Montaj Süresi", value: "5–7 İş Günü" },
      { label: "Garanti", value: "5 Yıl Yapısal Garanti" },
    ],
    highlights: [
      "Tüm mevsim kullanımına uygun özel profile sistemi",
      "Özelleştirilebilir renk ve doku seçenekleri",
      "Rüzgar ve deprem yüküne dayanıklı çelik bağlantı elemanları",
      "İsteğe bağlı ısıtma/soğutma entegrasyonu",
    ],
  },
  {
    title: "EKO Niş 35 Ahşap Ev",
    slug: "eko-nis-35-ahsap-ev",
    category: "Ahşap Ev",
    location: "Kayseri, Türkiye",
    year: 2026,
    description: "Minimalist, doğaya duyarlı ve sürdürülebilir yaşam alanı sunan ahşap ev.",
    image: "/images/projects/eko-nis-35-ahsap-ev.jpg",
    longDescription:
      "EKO Niş 35, 35 m² net yaşam alanında maksimum konforu sağlamak üzere tasarlanmıştır. Sertifikalı çevre dostu ahşap malzemeler, A+ enerji sınıfı yalıtım sistemi ve pasif solar tasarım prensiplerine dayanan bu model; hem gezgini hem de kalıcı yerleşimcileri hedeflemektedir.",
    features: [
      { label: "Malzeme", value: "FSC Sertifikalı Ladin" },
      { label: "Net Alan", value: "35 m²" },
      { label: "Duvar Kalınlığı", value: "140 mm Masif + 60 mm İzolasyon" },
      { label: "Enerji Sınıfı", value: "A+" },
      { label: "Taşıma Kapasitesi", value: "TIR ile Nakliye Uyumlu" },
      { label: "Garanti", value: "7 Yıl Yapısal Garanti" },
    ],
    highlights: [
      "Pasif solar tasarım ile enerji tüketimini minimize eder",
      "İç mekân yüksekliği 2,80 m ile ferah yaşam hissi",
      "Modüler genişleme desteği (ek oda, teras vb.)",
      "Geri dönüştürülmüş ve sürdürülebilir iç kaplama seçenekleri",
    ],
  },
  {
    title: "Bungalow Ev 4+1",
    slug: "bungalow-ev-4-1",
    category: "Bungalow",
    location: "Ankara, Türkiye",
    year: 2026,
    description: "Geniş aileler için tasarlanmış modern ve konforlu ahşap bungalow.",
    image: "/images/projects/modern-ahsap-kis-bahcesi.jpg",
    longDescription:
      "Bungalow Ev 4+1, 4 yatak odası ve geniş sosyal alanlara sahip aile odaklı yapı konseptimizin amiral gemisidir. Açık plan mutfak-oturma düzeni, çift cephe terası ve her odada klima alt yapısıyla kalıcı konut standardını karşılamaktadır.",
    features: [
      { label: "Oda Sayısı", value: "4+1" },
      { label: "Brüt Alan", value: "120 m²" },
      { label: "Ahşap Türü", value: "Kuzey Avrupa Sarıçamı" },
      { label: "Çatı Sistemi", value: "Alaturka Kiremit / Metal Seçenekli" },
      { label: "Tesisat", value: "Kombi + Yerden Isıtma Hazırlıklı" },
      { label: "Garanti", value: "10 Yıl Yapısal Garanti" },
    ],
    highlights: [
      "Çift cephe ahşap teras ve peyzaj entegrasyonu",
      "Sismik yüke dayanıklı çelik-ahşap karma iskelet",
      "Tadilatsız eşya transferine hazır anahtar-teslim seçeneği",
      "Opsiyonel çatı güneş paneli alt yapısı",
    ],
  },
  {
    title: "Tiny House Eko 8",
    slug: "tiny-house-eko-8",
    category: "Tiny House",
    location: "İzmir, Türkiye",
    year: 2026,
    description: "Taşınabilir, fonksiyonel ve ergonomik küçük ev çözümü.",
    image: "/images/projects/eko-nis-35-ahsap-ev.jpg",
    longDescription:
      "Tiny House Eko 8, yalnızca 8 m genişliğinde standart taşıma ruhsatına uygun chassis üzerine inşa edilmiştir. Akıllı depolama çözümleri, katlanır mobilyalar ve çok işlevli mekânlarla 'daha azla daha fazla' felsefesini somutlaştırır.",
    features: [
      { label: "Dış Genişlik", value: "2,55 m (Nakliye Standartı)" },
      { label: "Uzunluk", value: "8 m" },
      { label: "Yaşam Alanı", value: "~20 m² + Loft" },
      { label: "Chassis", value: "Galvanizli Çelik, 8 T Taşıma" },
      { label: "Elektrik", value: "Off-grid Solar Uyumlu" },
      { label: "Garanti", value: "5 Yıl Yapısal Garanti" },
    ],
    highlights: [
      "Standart TIR ruhsatıyla her yerde taşınabilir",
      "Loft yatak odası ile ekstra yaşam alanı",
      "Tam donanımlı kompakt mutfak ve banyo",
      "Off-grid solar ve yağmur suyu toplama entegrasyonu",
    ],
  },
  {
    title: "Antik Ahşap Kamelya",
    slug: "antik-ahsap-kamelya",
    category: "Kamelya",
    location: "Kayseri, Türkiye",
    year: 2026,
    description: "Geleneksel dokunuşlarla tasarlanmış, estetik ahşap kamelya uygulaması.",
    image: "/images/projects/modern-ahsap-kis-bahcesi.jpg",
    longDescription:
      "El oyması detaylar, antik bronz bağlantı elemanları ve koyu ceviz tonlarıyla bezenen bu kamelya; bahçenize klasik Anadolu mimarisinin özgün ruhunu katar. Tamamen elle şekillendirilen ahşap oyma yüzeyleri her projeye özel üretilmektedir.",
    features: [
      { label: "Malzeme", value: "Karaçam (El Oymalı Yüzey)" },
      { label: "Boyut", value: "4×4 m (Standart) / Özel ölçü" },
      { label: "Çatı Tipi", value: "Piramit / Konik Seçenekli" },
      { label: "Yüzey İşlemi", value: "Antik Vernik + UV Koruma" },
      { label: "Montaj Süresi", value: "2–3 İş Günü" },
      { label: "Garanti", value: "3 Yıl Yapısal Garanti" },
    ],
    highlights: [
      "El oyması özgün süsleme desenleri",
      "İstege bağlı cam panel ve perde sistemi",
      "Yaz-kış koşullarına dayanıklı özel vernik uygulaması",
      "Bahçe aydınlatma entegrasyonu",
    ],
  },
  {
    title: "Pikus Tiny House 800",
    slug: "pikus-tiny-house-800",
    category: "Tiny House",
    location: "Muğla, Türkiye",
    year: 2026,
    description: "Lüks ve konforu bir araya getiren üst segment tiny house projesi.",
    image: "/images/projects/eko-nis-35-ahsap-ev.jpg",
    longDescription:
      "Pikus Tiny House 800, serinin en üst segmentini temsil eder. 800 kg hafif chassis, panoramik tavan penceresi, tüm mobilyaları dahil anahtar-teslim teslimat ve akıllı ev sistemi entegrasyonuyla mobilite ile lüksü birleştirir.",
    features: [
      { label: "Chassis Kapasitesi", value: "800 kg (Ultra Hafif Alüminyum)" },
      { label: "Toplam Alan", value: "22 m² + Loft + Teras" },
      { label: "Pencere Sistemi", value: "Panoramik Çatı Feneri" },
      { label: "Akıllı Ev", value: "Wi-Fi Termostat + Aydınlatma Otomasyonu" },
      { label: "İç Kaplama", value: "Ladin Lambri + Mermer Görünümlü Kompakt" },
      { label: "Garanti", value: "7 Yıl Yapısal Garanti" },
    ],
    highlights: [
      "Panoramik çatı penceresi ile yıldızlı gökyüzü deneyimi",
      "Akıllı ev sistemi (ısı, ışık, güvenlik) entegrasyonu",
      "Mobilyalı anahtar-teslim teslimat seçeneği",
      "Yüksek performanslı ısı pompalı HVAC sistemi",
    ],
  },
];
